<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>DataDrivenTestingDemo</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>10</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>f5d8d63c-1b33-451b-bb97-95b6cfdb2e14</testSuiteGuid>
   <testCaseLink>
      <guid>62f0f614-d876-4385-b342-5dc083120358</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DataDrivenTestingDemo</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>1e266c67-510e-4e7f-86ca-89c0704b5e5d</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Login Credentials Data</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>1e266c67-510e-4e7f-86ca-89c0704b5e5d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>b31a44a5-d997-4154-bfa4-412443334077</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>1e266c67-510e-4e7f-86ca-89c0704b5e5d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>9157b98f-725c-4cf2-88a7-f1b4849714e1</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
