<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_My Leave</name>
   <tag></tag>
   <elementGuidId>e8b7c8af-3885-4c2b-abf5-acd76bb43453</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='menu_leave_viewMyLeaveList']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu_leave_viewMyLeaveList</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>da1d2ca9-f6b1-4291-9bb7-5afdbba1b94d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/index.php/leave/viewMyLeaveList/reset/1</value>
      <webElementGuid>496ac374-b833-4a50-9fa4-88ba18967848</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menu_leave_viewMyLeaveList</value>
      <webElementGuid>eba06f48-933c-4398-ab06-9248b79c7463</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>My Leave</value>
      <webElementGuid>b7df1198-086f-45ba-b767-bdce5a0f2872</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu_leave_viewMyLeaveList&quot;)</value>
      <webElementGuid>298d96a7-8100-4943-9499-7d739c66ad95</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='menu_leave_viewMyLeaveList']</value>
      <webElementGuid>88b815d0-d3d3-48e3-9205-186a09783d26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='mainMenuFirstLevelUnorderedList']/li[3]/ul/li[2]/a</value>
      <webElementGuid>bb877048-99ae-4e91-b930-e60ddf8d4e7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'My Leave')]</value>
      <webElementGuid>c0ad9de1-312f-4d4f-b2fb-ddce52d4d4de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apply'])[1]/following::a[1]</value>
      <webElementGuid>c7c2e7e2-8db7-459a-a0da-7cbbfb05df58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Leave'])[1]/following::a[2]</value>
      <webElementGuid>40f449b8-0ce5-4181-83d6-d5b1909ff76b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Entitlements'])[1]/preceding::a[2]</value>
      <webElementGuid>60065877-0023-4c47-9355-2893a9218d91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Employee Entitlements'])[1]/preceding::a[3]</value>
      <webElementGuid>a057c884-8b66-4754-a9c7-8f7efdcc82a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='My Leave']/parent::*</value>
      <webElementGuid>34878c3e-e011-4b60-b663-9b312481b765</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/index.php/leave/viewMyLeaveList/reset/1')]</value>
      <webElementGuid>a3cbc16b-9dde-4799-9eb9-a68e8b62fccd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/ul/li[2]/a</value>
      <webElementGuid>bc86f177-7dda-49f5-8a41-a693ed935043</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/index.php/leave/viewMyLeaveList/reset/1' and @id = 'menu_leave_viewMyLeaveList' and (text() = 'My Leave' or . = 'My Leave')]</value>
      <webElementGuid>5038c22d-1942-448c-837e-6433b1ca7efa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
